# Generated by Django 6.1.1 on 2026-10-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('estimate', 'Смета готова'), ('in_process', 'В работе'), ('completed', 'Завершен'), ('paid', 'Оплачен')], default='new', max_length=20),
        ),
    ]
