# Generated by Django 6.1.1 on 2026-10-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_object_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
