# Generated by Django 6.1.1 on 2026-10-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_object_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstage',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workstage',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
