# Generated by Django 6.1.1 on 2026-10-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_workstage_end_date_alter_workstage_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='price_per_m_p',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='area_m_p',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='unit',
            field=models.CharField(choices=[('m2', 'м²'), ('m_p', 'п.м.')], default='m2', max_length=10),
        ),
        migrations.AlterField(
            model_name='object',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
