# Generated by Django 6.1.1 on 2026-10-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_estimate_price_per_m_p_object_area_m_p_object_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='price_per_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
